- name: Check k8s cluster readiness
  hosts: kind_central
  become: true
  tasks:
  - name: Check k8s cluster readiness
    shell: |
      export KUBECONFIG=/root/admin.conf
      while true
      do
         kubectl get nodes | grep NotReady
         if [ "$?" != "0" ]; then
             break
         fi
         sleep 1
      done

  - name: Label nodes as workers
    shell: |
      export KUBECONFIG=/root/admin.conf
      for i in $(kubectl get nodes | grep worker | awk '{print $1}')
      do
          kubectl label nodes $i node-role.kubernetes.io/worker='' --overwrite
      done
      kubectl label node/ovn-worker node-role.kubernetes.io/worker-
      kubectl label node/ovn-worker2 node-role.kubernetes.io/worker-
