- name: Stop OVN control plane
  hosts: kind_central
  become: true
  tasks:
  - name: Start ovn-northd
    systemd:
      name: ovn-northd
      state: stopped

- name: Stop ovn-controllers
  hosts: kind_nodes
  become: true
  tasks:
  - name: Stop ovn-controllers
    systemd:
      name: ovn-controller
      state: stopped

- name: Stop openvswitch
  hosts: kind_workers
  become: true
  tasks:
  - name: Stop openvswitch
    systemd:
      name: openvswitch
      state: stopped
